# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20160207_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='logo',
            field=models.ImageField(default=1, upload_to='/tmp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='headshot',
            field=models.ImageField(null=True, upload_to='/tmp'),
        ),
    ]
