# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20160207_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
